# ENVIRONMENT IDENTIFIER
env: blue   # change: blue / green

# Deployment settings
replicas: 1

image:
  repository: asia-south1-docker.pkg.dev/s-0-009988/docker-images/blue-deployment
  tag: "" 
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
    
appName: blue-app

service:
  name: blue-service
  type: LoadBalancer
  port: 80
