apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "online-shop.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "online-shop.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "online-shop.fullname" . }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ include "online-shop.fullname" . }}
    spec:
      containers:
        - name: {{ include "online-shop.fullname" . }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
