apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-{{ .Values.color }}
  labels:
    app: myapp-{{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp-{{ .Values.color }}
  template:
    metadata:
      labels:
        app: myapp-{{ .Values.color }}
    spec:
      containers:
      - name: myapp
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: "{{ .Values.color }}"
        ports:
        - containerPort: 8080
