replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/s-0-009988/docker-images/green
  #tag: "v3"
  pullPolicy: IfNotPresent
  
appName: myapp
service:
  name: green
  type: LoadBalancer
  port: 8080


