replicas: 2

image:
  repository: asia-south1-docker.pkg.dev/s-0-009988/docker-images/blue-deployment
  tag: ""
  pullPolicy: IfNotPresent

appName: blue
service:
  name: blue
  type: LoadBalancer
  port: 80
