
image:
  repository: asia-south1-docker.pkg.dev/s-0-009988/docker-images/blue-deployment
  tag: ""
  pullPolicy: IfNotPresent

  replicas: 2

appName: myapp
service:
  name: myapp
  type: LoadBalancer
  port: 80
