apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-stable
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: my-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service-stable
            port:
              number: 80


              nginx.ingress.kubernetes.io/canary: "false"
