apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-stable
  annotations:
    nginx.ingress.kubernetes.io/canary: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: */*
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service-stable
            port:
              number: 80
